services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
    env_file:
      - ./backend/.env
    volumes:
      - ./app:/srv/app
      - ./data/uploads:/srv/app/public/uploads
    command: ["npm","run","start"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
